name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: echo "No tests configured" # Or replace with: npm test 

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_SECERT_NAME }}/nodejs-demo-app:latest .

    - name: DockerHub Login
      run: echo "${{ secrets.DOCKER_SECERT_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_SECERT_NAME }}" --password-stdin

    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKER_SECERT_NAME }}/nodejs-demo-app:latest
